[props.displayId]
type = "string"

[props.category]
type = "int"
min = 0
max = 256

[props.name]
type = "string"
minLength = 1
maxLength = 256

[props.description]
type = "string"
minLength = 1
maxLength = 1000

[props.credits]
type = "int"
min = 0
max = 50
