// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import CourseSearchRequest from "./CourseSearchRequest.model"

export class ParseError extends Error {
  constructor (message: string) {
    super("parseCourseSearchRequest ParseError: " + message)
  }
}

export default function parseCourseSearchRequest (data: any) {
  if (typeof data !== "object") {
    throw new ParseError("Given data is not an object. " + String(data))
  }
  const query: string = data["query"]
  if (typeof query !== "string") {
    throw new ParseError("query is not a string")
  }
  return new CourseSearchRequest(
    query,
  )
}
