// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.


export class UnexpectedNullError extends Error {
  constructor () {
    super("Name UnexpectedNullError: If you see this, generated code by modelgun may be broken.")
  }
}

export class InvalidPropertyError extends Error {
  constructor (message: string) {
    super("Name InvalidPropertyError: " + message)
  }
}

/**
 * Name model.
 * 
 */
export default class Name {
  #first: string | null = null
  #last: string | null = null

  /**
   * @param string first 
   * @param string last 
   */
  constructor (
    first: string,
    last: string,
  ) {
    this.setFirst(first)
    this.setLast(last)
  }

  /**
   * Gets first
   */
  getFirst (): string {
    if (this.#first === null) {
      throw new UnexpectedNullError()
    }
    return this.#first
  }

  /**
   * Checks first
   */
  checkFirst (value: string) {
  }

  /**
   * Sets first
   * @param value
   */
  setFirst (value: string) {
    this.checkFirst(value)
    this.#first = value
  }

  /**
   * Gets last
   */
  getLast (): string {
    if (this.#last === null) {
      throw new UnexpectedNullError()
    }
    return this.#last
  }

  /**
   * Checks last
   */
  checkLast (value: string) {
  }

  /**
   * Sets last
   * @param value
   */
  setLast (value: string) {
    this.checkLast(value)
    this.#last = value
  }

  /**
   * Clones 
   */
  clone (shallow: boolean) {
    return new Name (
      this.getFirst(),
      this.getLast(),
    )
  }

  /**
   * Creates an object.
   */
  toObject () {
    return {
      first: this.getFirst(),
      last: this.getLast(),
    }
  }
}
