// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import Name from "./Name.model"

export class ParseError extends Error {
  constructor (message: string) {
    super("parseName ParseError: " + message)
  }
}

export default function parseName (data: any) {
  if (typeof data !== "object") {
    throw new ParseError("Given data is not an object. " + String(data))
  }
  const first: string = data["first"]
  if (typeof first !== "string") {
    throw new ParseError("first is not a string")
  }
  const last: string = data["last"]
  if (typeof last !== "string") {
    throw new ParseError("last is not a string")
  }
  return new Name(
    first,
    last,
  )
}
