// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import Term from "./Term.model"

export class ParseError extends Error {
  constructor (message: string) {
    super("parseTerm ParseError: " + message)
  }
}

export default function parseTerm (data: any) {
  if (typeof data !== "object") {
    throw new ParseError("Given data is not an object. " + String(data))
  }
  const id: string = data["id"]
  if (typeof id !== "string") {
    throw new ParseError("id is not a string")
  }
  const name: string = data["name"]
  if (typeof name !== "string") {
    throw new ParseError("name is not a string")
  }
  const grade: number = data["grade"]
  if (typeof grade !== "number") {
    throw new ParseError("grade is not a number")
  }
  return new Term(
    id,
    name,
    grade,
  )
}
