// This file is generated by model file generator.
// Please do NOT edit.

import Name from "./Name"
import isUuid from "validator/es/lib/isUuid"
import {
  UnexpectedNullError,
  InvalidPropertyError,
} from "./errors"

export default class Account {
  #id: string | null = null
  #type: number | null = null
  #name: Name | null = null

  constructor (
    id: string,
    type: number,
    name: Name,
  ) {
    this.setId(id)
    this.setType(type)
    this.setName(name)
  }

  getId (): string {
    if (this.#id === null) {
      throw new UnexpectedNullError()
    }
    return this.#id
  }

  setId (value: string) {
    if (!isUuid(value)) {
      throw new InvalidPropertyError()
    }
    this.#id = value
  }

  getType (): number {
    if (this.#type === null) {
      throw new UnexpectedNullError()
    }
    return this.#type
  }

  setType (value: number) {
    this.#type = value
  }

  getName (): Name {
    if (this.#name === null) {
      throw new UnexpectedNullError()
    }
    return this.#name
  }

  setName (value: Name) {
    this.#name = value
  }
}
