// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import faker from "faker"
import Account from "./Account.model"
import Name from "./Name.model"
import fakeName from "./Name.faker"

export class FakeError extends Error {
  constructor (message: string) {
    super("fakeAccount FakeError: " + message)
  }
}

export default function fakeAccount (data?: any): Account {
  if (data && typeof data !== "object") {
    throw new FakeError("Given data is not an object. " + String(data))
  }
  const id: string = data["id"] || faker.datatype.uuid()
  if (typeof id !== "string") {
    throw new FakeError("id is not a string")
  }
  const type: number = data["type"] || faker.datatype.number()
  if (typeof type !== "number") {
    throw new FakeError("type is not a number")
  }
  const name: Name = fakeName(data["name"])
  const email: string = data["email"] || faker.internet.email()
  if (typeof email !== "string") {
    throw new FakeError("email is not a string")
  }
  return new Account(
    id,
    type,
    name,
    email,
  )
}
