
[props.id]
type = "uuid"
faker = "datatype.uuid"

[props.type]
type = "int"
candidates = [0, 1, 2]
faker = "datatype.number"

[props.name]
type = "ref:Name"
minLength = 1
maxLength = 256
faker = "name.findName"

[props.email]
type = "email"
faker = "internet.email"
