// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import isUuid from "validator/lib/isUuid"

export class UnexpectedNullError extends Error {
  constructor () {
    super("CourseRegistration UnexpectedNullError: If you see this, generated code by modelgun may be broken.")
  }
}

export class InvalidPropertyError extends Error {
  constructor (message: string) {
    super("CourseRegistration InvalidPropertyError: " + message)
  }
}

/**
 * CourseRegistration model.
 * Course Registation
 */
export default class CourseRegistration {
  #id: string | null = null
  #courseId: string | null = null
  #studentId: string | null = null

  /**
   * @param string id 
   * @param string courseId 
   * @param string studentId 
   */
  constructor (
    id: string,
    courseId: string,
    studentId: string,
  ) {
    this.setId(id)
    this.setCourseId(courseId)
    this.setStudentId(studentId)
  }

  /**
   * Gets id
   */
  getId (): string {
    if (this.#id === null) {
      throw new UnexpectedNullError()
    }
    return this.#id
  }

  /**
   * Checks id
   */
  checkId (value: string) {
    if (!isUuid(value)) {
      throw new InvalidPropertyError(`${value} is not UUID value. (CourseRegistration.setId)`)
    }
  }

  /**
   * Sets id
   * @param value
   */
  setId (value: string) {
    this.checkId(value)
    this.#id = value
  }

  /**
   * Gets courseId
   */
  getCourseId (): string {
    if (this.#courseId === null) {
      throw new UnexpectedNullError()
    }
    return this.#courseId
  }

  /**
   * Checks courseId
   */
  checkCourseId (value: string) {
  }

  /**
   * Sets courseId
   * @param value
   */
  setCourseId (value: string) {
    this.checkCourseId(value)
    this.#courseId = value
  }

  /**
   * Gets studentId
   */
  getStudentId (): string {
    if (this.#studentId === null) {
      throw new UnexpectedNullError()
    }
    return this.#studentId
  }

  /**
   * Checks studentId
   */
  checkStudentId (value: string) {
  }

  /**
   * Sets studentId
   * @param value
   */
  setStudentId (value: string) {
    this.checkStudentId(value)
    this.#studentId = value
  }

  /**
   * Clones 
   */
  clone (shallow: boolean) {
    return new CourseRegistration (
      this.getId(),
      this.getCourseId(),
      this.getStudentId(),
    )
  }

  /**
   * Creates an object.
   */
  toObject () {
    return {
      id: this.getId(),
      courseId: this.getCourseId(),
      studentId: this.getStudentId(),
    }
  }
}
