// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import CourseRegistration from "./CourseRegistration.model"

export class ParseError extends Error {
  constructor (message: string) {
    super("parseCourseRegistration ParseError: " + message)
  }
}

export default function parseCourseRegistration (data: any) {
  if (typeof data !== "object") {
    throw new ParseError("Given data is not an object. " + String(data))
  }
  const id: string = data["id"]
  if (typeof id !== "string") {
    throw new ParseError("id is not a string")
  }
  const courseId: string = data["courseId"]
  if (typeof courseId !== "string") {
    throw new ParseError("courseId is not a string")
  }
  const studentId: string = data["studentId"]
  if (typeof studentId !== "string") {
    throw new ParseError("studentId is not a string")
  }
  return new CourseRegistration(
    id,
    courseId,
    studentId,
  )
}
