// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import faker from "faker"
import CourseRegistration from "./CourseRegistration.model"

export class FakeError extends Error {
  constructor (message: string) {
    super("fakeCourseRegistration FakeError: " + message)
  }
}

export default function fakeCourseRegistration (data?: any): CourseRegistration {
  if (data && typeof data !== "object") {
    throw new FakeError("Given data is not an object. " + String(data))
  }
  const id: string = data["id"] || faker.()
  if (typeof id !== "string") {
    throw new FakeError("id is not a string")
  }
  const courseId: string = data["courseId"] || faker.()
  if (typeof courseId !== "string") {
    throw new FakeError("courseId is not a string")
  }
  const studentId: string = data["studentId"] || faker.()
  if (typeof studentId !== "string") {
    throw new FakeError("studentId is not a string")
  }
  return new CourseRegistration(
    id,
    courseId,
    studentId,
  )
}
