// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.


export class UnexpectedNullError extends Error {
  constructor () {
    super("CourseSearchRequest UnexpectedNullError: If you see this, generated code by modelgun may be broken.")
  }
}

export class InvalidPropertyError extends Error {
  constructor (message: string) {
    super("CourseSearchRequest InvalidPropertyError: " + message)
  }
}

/**
 * CourseSearchRequest model.
 * 
 */
export default class CourseSearchRequest {
  #query: string | null = null

  /**
   * @param string query 
   */
  constructor (
    query: string,
  ) {
    this.setQuery(query)
  }

  /**
   * Gets query
   */
  getQuery (): string {
    if (this.#query === null) {
      throw new UnexpectedNullError()
    }
    return this.#query
  }

  /**
   * Checks query
   */
  checkQuery (value: string) {
  }

  /**
   * Sets query
   * @param value
   */
  setQuery (value: string) {
    this.checkQuery(value)
    this.#query = value
  }

  /**
   * Clones 
   */
  clone (shallow: boolean) {
    return new CourseSearchRequest (
      this.getQuery(),
    )
  }

  /**
   * Creates an object.
   */
  toObject () {
    return {
      query: this.getQuery(),
    }
  }
}
