// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import CreateAccountRequest from "./CreateAccountRequest.model"

export class ParseError extends Error {
  constructor (message: string) {
    super("parseCreateAccountRequest ParseError: " + message)
  }
}

export default function parseCreateAccountRequest (data: any) {
  if (typeof data !== "object") {
    throw new ParseError("Given data is not an object. " + String(data))
  }
  const type: number = data["type"]
  if (typeof type !== "number") {
    throw new ParseError("type is not a number")
  }
  const email: string = data["email"]
  if (typeof email !== "string") {
    throw new ParseError("email is not a string")
  }
  return new CreateAccountRequest(
    type,
    email,
  )
}
