// This file is generated by model file generator.
// Please do NOT edit.

import {
  UnexpectedNullError,
  InvalidPropertyError,
} from "./errors"

export default class Name {
  #first: string | null = null
  #last: string | null = null

  constructor (
    first: string,
    last: string,
  ) {
    this.setFirst(first)
    this.setLast(last)
  }

  getFirst (): string {
    if (this.#first === null) {
      throw new UnexpectedNullError()
    }
    return this.#first
  }

  setFirst (value: string) {
    this.#first = value
  }

  getLast (): string {
    if (this.#last === null) {
      throw new UnexpectedNullError()
    }
    return this.#last
  }

  setLast (value: string) {
    this.#last = value
  }
}
