// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import faker from "faker"
import Name from "./Name.model"

export class FakeError extends Error {
  constructor (message: string) {
    super("fakeName FakeError: " + message)
  }
}

export default function fakeName (data?: any): Name {
  if (data && typeof data !== "object") {
    throw new FakeError("Given data is not an object. " + String(data))
  }
  const first: string = data["first"] || faker.()
  if (typeof first !== "string") {
    throw new FakeError("first is not a string")
  }
  const last: string = data["last"] || faker.()
  if (typeof last !== "string") {
    throw new FakeError("last is not a string")
  }
  return new Name(
    first,
    last,
  )
}
