// This file is auto-generated by ModelGun code generator.
// https://github.com/ku6ryo/ModelGun
// PLEASE DO NOT EDIT. If you want to extend the functionality, please import
// the export members and use as a part or inherit class.

import faker from "faker"
import Term from "./Term.model"

export class FakeError extends Error {
  constructor (message: string) {
    super("fakeTerm FakeError: " + message)
  }
}

export default function fakeTerm (data?: any): Term {
  if (data && typeof data !== "object") {
    throw new FakeError("Given data is not an object. " + String(data))
  }
  const id: string = data["id"] || faker.()
  if (typeof id !== "string") {
    throw new FakeError("id is not a string")
  }
  const name: string = data["name"] || faker.()
  if (typeof name !== "string") {
    throw new FakeError("name is not a string")
  }
  const grade: number = data["grade"] || faker.()
  if (typeof grade !== "number") {
    throw new FakeError("grade is not a number")
  }
  return new Term(
    id,
    name,
    grade,
  )
}
