name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-16.04
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install npm packages
        run: yarn install
      - name: Creates sqlite db
        run: yarn ts-node node_modules/typeorm/cli.js migration:run
      - name: Test
        run: yarn test
